account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='account/change_password.html'),
         name='password_change'),
    path('change_password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='account/change_password_done.html'),
         name='password_change_done'),

    path('reset_password/', PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_done/', PasswordChangeDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('active/<uidb64>/<token>', views.ActiveAccountView.as_view(), name='active'),
    # profile
    path('profile', views.profile, name='profile_page'),
    path('update_user_information/', views.update_user_information, name='update_user_information'),
    path('update_project/<int:project_id>/', views.update_project, name='update_project'),
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('update_donation/<int:donation_id>/', views.update_donation, name='update_donation'),
    path('delete_donation/<int:donation_id>/', views.delete_donation, name='delete_donation'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('update_user_avatar/<int:user_id>/', views.update_user_avatar, name='update_user_avatar')
]

crowdfunding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from project import views

urlpatterns = [
    path('', views.index, name="home"),
    path('create_project/', views.create_project, name="create_project"),
    path('project/<int:project_id>', views.project_detail, name="project_detail"),
    path('project/report/', views.project_report, name='project_report'),
    path('comment_report/<int:comment_id>', views.comment_report, name='project_report_comment'),
    path('project/<int:project_id>/post_comment', views.post_comment, name="post_comment"),
    path('project/<int:project_id>/fund', views.fund_project, name="project_fund"),

    path('create_project/', views.create_project, name="create_project"),
    path('project/<int:project_id>', views.project_detail, name="project_detail"),
    path('project_rate/<int:project_id>/<int:rating_val>', views.rating_project, name="rating_project"),
    path('projects/', views.all_projects, name='projects'),
    path('projects/category/<category_id>', views.projects_by_category, name='projects_by_category'),
    path('projects/tag/<int:tag_id>', views.projects_by_tag, name='projects_by_tag'),
    path('projects/search/', views.projects_search, name='projects_search'),
]

project/models.py
from django.db import models
from account.models import MyUser
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    title = models.CharField(max_length=70)
    details = models.TextField()

    def __str__(self):
        return self.title


class Project(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=70)
    details = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    total_target = models.DecimalField(max_digits=10, decimal_places=2)
    start_date = models.DateField()
    end_date = models.DateField()
    tags = TaggableManager()
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # for get this tags from template as strings
    def get_tags(self):
        tags = ""
        for tag in self.tags.all():
            tags += f'{tag},'
        return tags

    def get_absolute_url(self):
        return reverse('home')

    # calc number of rating for project
    def number_of_rating(self):
        # rating = Rate.objects.filter(project=self)
        return Rate.objects.filter(project=self).count()

    # calc average rating
    def average_rating(self):
        sum = 0
        rating = Rate.objects.filter(project=self)
        for rate in rating:
            sum += rate.rating
        if len(rating):
            return sum / len(rating)
        return 0

    def donation_collect(self):
        sum = 0
        donations = Denote.objects.filter(project=self)
        for donation in donations:
            sum += donation.amount
        return sum

    class Meta:
        constraints = [
            models.CheckConstraint(name='end_date_after_start_date',
                                   check=models.Q(end_date__gt=models.F('start_date')))
        ]

    def __str__(self):
        return self.title


class ProjectPicture(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='projects/')


class Comment(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    body = models.CharField(max_length=250)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Reply(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    body = models.CharField(max_length=250)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Denote(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_photo(self):
        if ProjectPicture.objects.filter(project=self.project):
            return ProjectPicture.objects.filter(project=self.project).first().image
        return False


class Rate(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ])
    created_at = models.DateTimeField(auto_now_add=True)

    # for unique (user and project) 
    class Meta:
        unique_together = (('user', 'project'),)
        index_together = (('user', 'project'),)


class ProjectReport(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    body = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)


class CommentReport(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    body = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)

# class UserProfile(models.Model):
#     user  = models.OneToOneField(User)
#     avatar= models.ImageField()

project/forms.py
from django import forms
from project.models import Project, ProjectPicture
from django.forms.widgets import DateInput
from django.core.files.images import get_image_dimensions
# from project.models import UserProfile


class ProjectForm(forms.ModelForm):
    images = forms.ImageField(widget=forms.FileInput(attrs={'multiple': True}), required=True, help_text="you can upload more than one image")

    def clean(self):
        start_date = self.cleaned_data.get("start_date")
        end_date = self.cleaned_data.get("end_date")
        if end_date and start_date and end_date < start_date:
            msg = u"End date should be greater than start date."
            self._errors["end_date"] = self.error_class([msg])

    class Meta:
        model = Project
        fields = ['title', 'details', 'total_target', 'start_date', 'end_date', 'tags', 'category']
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date': DateInput(attrs={'type': 'date'})
        }

project/views.py
from django.contrib.auth.decorators import login_required

from django.db.models import Sum, Q, Avg
from django.db.models.functions import Coalesce
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from .models import Project, ProjectPicture, Category, ProjectReport, Comment, CommentReport, Denote

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from .models import Project, ProjectPicture, Category, Rate

from .forms import ProjectForm
from django.contrib import messages
from django.contrib.auth.models import User
from taggit.models import Tag
from django.template.defaultfilters import slugify
from django.conf import settings
from django.contrib.auth import login
from django.core.mail import send_mail

# Create your views here.


def index(request):
    latest_projects = Project.objects.all().order_by('-start_date')[:5]
    latest_featured_projects = Project.objects.filter(is_featured=True).order_by('-start_date')[:5]
    top_rated_projects = Project.objects.annotate(rate_avg=Coalesce(Avg('rate__rating'), 0)).order_by('-rate_avg')[:3]
    context = {
        'latest_projects': latest_projects,
        'latest_featured_projects': latest_featured_projects,
        'top_rated_projects': top_rated_projects
    }
    return render(request, 'project/index.html', context)


@login_required
def create_project(request):
    form = ProjectForm()
    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.user = request.user
            # project.slug = slugify(project.title)
            project.save()
            form.save_m2m()
            for image in request.FILES.getlist('images'):
                ProjectPicture.objects.create(project=project, image=image)
            messages.success(request, 'project has been created')
            return redirect('home')
        return render(request, 'project/createproject.html', {"form": form})
    return render(request, 'project/createproject.html', {"form": form})


def project_detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    realted_projects = Project.objects.filter(tags__in=project.tags.all()).exclude(id=project.id).order_by('-created_at')[:4]
    context = {
        "project": project,
        "project_target_collected": Denote.objects.filter(project=project).aggregate(Sum('amount'))[
                                        'amount__sum'] or 0.0,
        'realted_projects': realted_projects
    }
    return render(request, 'project/project_detail.html', context)


@login_required
def project_report(request):
    rec = ProjectReport.objects.create(user=request.user, body=request.GET.get('body'),
                                       project_id=request.GET.get('project'))
    if rec:
        data = {'return': True}
    else:
        data = {'return': False}
    return JsonResponse(data)


@login_required
def post_comment(request, project_id):
    if request.method == "POST":
        if Project.objects.filter(pk=project_id).exists():
            comment = Comment.objects.create(body=request.POST.get('comment-body'), user=request.user,
                                             project_id=project_id)
    return redirect('project_detail', project_id)


def comment_report(request, comment_id):
    if Comment.objects.filter(pk=comment_id).exists():
        rec = CommentReport.objects.create(body=request.GET.get('body'), user=request.user, comment_id=comment_id)
        return JsonResponse({"return": True})
    return JsonResponse({"return": False})


@login_required
def fund_project(request, project_id):
    if request.method == 'POST':
        if Project.objects.filter(pk=project_id).exists():
            project = Project.objects.get(pk=project_id)
            if not request.POST.get('amount').isdigit():
                messages.success(request, 'error submitting the fund, Invalid Money amount')
                return redirect('project_detail', project_id)
            if project.user.id == request.user.id:
                messages.success(request, 'You can not fund your own project')
                return redirect('project_detail', project_id)

            project_funds = Denote.objects.filter(project_id=project_id).aggregate(Sum('amount'))['amount__sum'] or 0
            if project_funds + int(request.POST.get('amount')) < project.total_target:
                rec = Denote.objects.create(user=request.user, project_id=project_id, amount=request.POST.get('amount'))
                if rec:
                    messages.success(request, 'Your fund has been submitted')
                    return redirect('project_detail', project_id)
                else:
                    messages.success(request, 'error submitting the fund')
                    return redirect('project_detail', project_id)
            else:
                messages.success(request,
                                 'the project has been collected all total '
                                 'target or your amount is much for the project')
                return redirect('project_detail', project_id)


@login_required
def rating_project(request, project_id, rating_val):
    # user = get_object_or_404(User, pk=request.user.id)
    # project = get_object_or_404(Project, pk=project_id)

    try:
        # if user update his rating 
        rating = Rate.objects.get(user=request.user, project_id=project_id)
        rating.rating = rating_val
        rating.save()
        message = {
            'status': 'update rating',
            'number_of_rating': rating.project.number_of_rating()
        }
    except:
        # user make first rating on this project
        rating = Rate(user=request.user, project_id=project_id, rating=rating_val)
        rating.save()
        message = {
            'status': 'new rating',
            'number_of_rating': rating.project.number_of_rating(),
        }

    return JsonResponse(message)


def all_projects(request):
    projects = Project.objects.all().order_by('-start_date')[:3]
    return render(request, 'project/projects.html', {'projects': projects})


def projects_by_category(request, category_id):
    projects = Project.objects.filter(category_id=category_id)
    return render(request, 'project/projects.html', {'projects': projects})

def projects_by_tag(request, tag_id):
    projects = Project.objects.filter(tags__id__in=[tag_id])
    return render(request, 'project/projects.html', {'projects': projects})

def projects_search(request):
    q = request.GET.get('q') # extract optional arguments

    projects = Project.objects.filter(Q(title__icontains=q) | Q(details__icontains=q))
    return render(request, 'project/projects.html', {'projects': projects})

project/templates/project/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Home
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'project/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'project/css/tagsinput.css' %}">


</head>

<body>

{% block header %}
{% include 'project/include/header.html' %}
{% endblock %}
<div class="container">
    <div class="row my-5">
        {% block content %}
            this is block
        {% endblock %}
    </div>

</div>

{% include 'project/include/footer.html' %}

<script src="{% static 'project/js/tagsinput.js' %}"></script>
<script src="{% static 'project/js/scripts.js' %}"></script>
<script src="{% static 'project/js/account_scripts.js' %}"></script>
</body>
</html>

project/templates/project/createproject.html
{% extends 'project/base.html' %}

{% block title %}
Create New Project
{% endblock %}

{% block header %}
{% include 'project/include/header.html' %}
{% endblock %}


{% block content %}
<div class="col-12 mt-3">
    <h2 class="alert alert-info">Create New Project</h2>
</div>
<div class="col-8 my-3">


<form novalidate method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% include 'project/include/form.html' %}
    <button type="submit" class="btn btn-primary">Submit</button>

</form>
</div>
{% endblock %}

project/templates/project/index.html
{% extends 'project/base.html' %}
{% load static %}



{% block header %}
{% include 'project/include/header.html' %}
<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    {% for _ in top_rated_projects %}
    <li data-target="#demo" data-slide-to="{{forloop.counter0}}"  {% if not forloop.counter0 %} class="active"{% endif %}></li>
    {% endfor %}
  </ul>
  <div class="carousel-inner">
    {% for project in top_rated_projects %}
    <div class="carousel-item {% if not forloop.counter0 %}  active {%endif%}">
      <img src="{{ project.projectpicture_set.first.image.url }}" alt="Los Angeles">
      <div class="carousel-caption" style="background-color:rgba(0,0,0,.5)">
        <h3>{{project.title}}</h3>
        <p>{{project.details}}</p>
      </div>
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
{% endblock %}

{% block content %}

<div class="row" style="justify-content: center;">
  <div class="col-12">
    <h1 class="text-center p-5">latest 5 projects</h1>
  </div>
  {% for project in latest_projects %}
  <div class="col-md-2  mr-3">
    <div class="card" style="width: 12rem;">
      {% if project.projectpicture_set.first %}
      <img width="140" height="110" src="{{ project.projectpicture_set.first.image.url }}" class="card-img-top" alt="{{project.title}}">
      {% else %}
      <img width="140" height="110" src="https://via.placeholder.com/140x100" class="card-img-top" alt="{{project.title}}">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{project.title}}</h5>
        <p class="card-text">{{ project.details|slice:":10" }}...</p>
        <a href="{% url 'project_detail' project.id %}" class="btn btn-primary">more</a>
      </div>
    </div>
  </div>
  {% endfor %}

</div>

<div class="row" style="justify-content: center;">
  <div class="col-12">
    <h1 class="text-center p-5">latest 5 featured projects</h1>
  </div>
  {% for project in latest_featured_projects %}
  <div class="col-md-2  mr-3">
    <div class="card" style="width: 12rem;">
      {% if project.projectpicture_set.first %}
      <img width="140" height="110" src="{{ project.projectpicture_set.first.image.url }}" class="card-img-top" alt="{{project.title}}">
      {% else %}
      <img width="140" height="110" src="https://via.placeholder.com/140x100" class="card-img-top" alt="{{project.title}}">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{project.title}}</h5>
        <p class="card-text">{{ project.details|slice:":10" }}...</p>
        <a href="{% url 'project_detail' project.id %}" class="btn btn-primary">more</a>
      </div>
    </div>
  </div>
  {% endfor %}

</div>


{% if messages %}
  {% for msg in messages %}
  <div class="toast" aria-live="polite" aria-atomic="true" data-delay="10000"
    style="position: fixed; top: 100px; right: 10px;">
    <div class="toast-header">
      <strong class="mr-auto text-primary">{{msg.tags}}</strong>
      <small class="text-muted">5 mins ago</small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
    </div>
    <div class="toast-body">
      {{msg}}
    </div>
  </div>
  {% endfor %}
{% endif %}

<script>
  $(document).ready(function () {
    $('.toast').toast('show');
  })
</script>
{% endblock %}

project/templates/project/project_detail.html
{% extends 'project/base.html' %}

{% block title %}
Project {{ project.title }}
{% endblock %}

{% block header %}
{% include 'project/include/header.html' %}
{% endblock %}


{% block content %}
<div class="col-12">
    <h2 class="">{{ project.title }}</h2>
    <small class="text-muted">from {{ project.start_date }} to {{ project.end_date }} by <a href="#">{{ project.user.first_name }}</a></small>
</div>
<div class="col-8">

    {% for tag in project.tags.all %}
    <a class="badge badge-{% cycle 'primary' 'success' %} p-2" href="{% url 'projects_by_tag' tag.id %}">{{ tag.name }}</a>
    {% endfor %}

    <p>project category <a href="#">{{ project.category.title }}</a></p>
    <p>total target: {{ project.total_target }}</p>
    <p>collected: {{ project_target_collected }}</p>
    <p>average rating: {{ project.average_rating }} by {{ project.number_of_rating }} user(s)</p>
    <div id="demo" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            {% for img in project.projectpicture_set.all %}
            <li data-target="#demo" data-slide-to="{{ forloop.counter0 }}"
                class="{% if forloop.counter0 == 0 %}active {% endif %}"></li>
            {% endfor %}
        </ul>
        <div class="carousel-inner">
            {% for img in project.projectpicture_set.all %}
            <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                <img src="{{ img.image.url }}" alt="{{ project.title }}">
            </div>
            {% endfor %}

        </div>
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>

    <!-- make rate -->
    <div class="row mt-3">
        <div class="col-4">
            <h4>project details</h4>
        </div>
        {% if user.is_authenticated and project.user != user %}
        <div class="col-6">
            <!--just make it to handle average_rating from project to js file -->
            <span id="average_rating"
                  onclick="get_average_rating('{{ project.average_rating }}' , '{{ project.number_of_rating }}')"></span>
            <div id="review" class="text-center mx-2"></div>

        </div>
        <div class="col-2 mt-2">
            <span style="font-weight: bold;font-size: larger;">(</span>
            <span id="rating_num_value"
                  style="font-weight: bold;font-size: larger;">{{project.number_of_rating}}</span>
            <span style="font-weight: bold;font-size: larger;">)</span>
        </div>
        {% endif %}
    </div>

    <!--   -->
    <p>
        {{project.details}}
    </p>
    <!-- Button report project -->
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
        report
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Project Report</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="project_id" value="{{project.id}}">
                    <textarea placeholder="Write your message" id="report-message" name="report-message" cols="30"
                              class="w-100"></textarea>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="project-report-btn" class="btn btn-primary">Send</button>
                </div>
            </div>
        </div>
    </div>
    {# Commentes #}
    <hr>
    <h3>Comments</h3>
    {% for comment in project.comment_set.all %}
    <div class="media">
        <img src="https://via.placeholder.com/65x65" class="mr-3" alt="...">
        <div class="media-body">
            <h5 class="mt-0"><a href="#">{{ comment.user.username }}</a></h5>
            <small class="text-muted d-block">{{comment.created_at}}</small>
            <p>{{ comment.body }}</p>
            <a data-toggle="modal" data-created-by="{{ comment.user.first_name }}" data-comment="{{comment.id}}"
               data-target="#commentReportModal" class="report-link text-danger">report</a>
        </div>
    </div>
    {% endfor %}
    <hr>
    <div class="media mt-3">
        <div class="media-body">
            <form method="post" action="{% url 'post_comment' project.id %}">
                {% csrf_token %}
                <input type="hidden" name="next" value="/project/{{project.id}}">
                <textarea name="comment-body" id="comment-body" class="w-100" rows="5"></textarea>
                <button type="submit" class="btn btn-primary">comment</button>
            </form>
        </div>
    </div>
    <!--  comment report modal  -->
    <div class="modal fade" id="commentReportModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title mr-1" id="commentReportLabel">Comment Report</h5>
                    <small style="align-self: flex-end;" class="created-by text-muted d-block"></small>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <textarea placeholder="Write your message" id="commentReportMessage" name="report-message" cols="30"
                              class="w-100"></textarea>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="commentReportBtn" class="btn btn-primary">Send</button>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="col-4">
    {% ifnotequal project.user user %}
    <div>
        <h3>Fund for this project</h3>
        <form class="form" method="post" action="{% url 'project_fund' project.id %}">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" placeholder="amount" type="number" step="0.01" name="amount">
            </div>
            <input type="submit" value="submit" class="btn btn-success btn-block"/>
        </form>
    </div>
    {% endifnotequal %}
</div>

<div class="col-12">
    <div class="row mt-3">
        <div class="col-12">
            <h3>Related Projects</h3>
        </div>
        {% for project in realted_projects %}
        <div class="col-md-2  mr-3">
            <div class="card" style="width: 12rem;">
                {% if project.projectpicture_set.first %}
                <img width="140" height="110" src="{{ project.projectpicture_set.first.image.url }}"
                     class="card-img-top" alt="{{project.title}}">
                {% else %}
                <img width="140" height="110" src="https://via.placeholder.com/140x100" class="card-img-top"
                     alt="{{project.title}}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{project.title}}</h5>
                    <p class="card-text">{{ project.details|slice:":10" }}...</p>
                    <a href="{% url 'project_detail' project.id %}" class="btn btn-primary">more</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="alert alert-info col-12 text-center">
            <p>There are no related projects</p>
        </div>
        {% endfor %}
    </div>
</div>
<div id="report-toast" class="toast" aria-live="polite" aria-atomic="true" data-delay="10000"
     style="position: fixed; top: 100px; right: 10px;">
    <div class="toast-header">
        <strong class="mr-auto text-primary">Success</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
    </div>
    <div class="toast-body">
        report has been submitted, thanks for telling us
    </div>
</div>

{% if messages %}
{% for msg in messages %}
<div class="toast" aria-live="polite" aria-atomic="true" data-delay="10000"
     style="position: fixed; top: 100px; right: 10px;">
    <div class="toast-header">
        <strong class="mr-auto text-primary">{{msg.tags}}</strong>
        <small class="text-muted">5 mins ago</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
    </div>
    <div class="toast-body">
        {{msg}}
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

project/templates/project/projects.html
{% extends 'project/base.html' %}

{% block title%}
projects
{% endblock %}
{% block content %}
<div>
    {% for project in projects %}
        <p>{{ project.title }}</p>
        <p>{{ project.details }}</p>
        <p>{{ project.start_date }}</p>
        <p>{{ project.end_date }}</p>
        {% if not forloop.last %}
            <hr>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}